# Generated by Django 3.2.12 on 2022-03-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0005_visitorlog_status_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="max_number_of_visits",
            field=models.IntegerField(
                default=3,
                help_text="After the visitor uses the link this amount of times, the link becomes disabled",
                null=True,
            ),
        ),
    ]
